CREATE TABLE charts (
  name VARCHAR(255) PRIMARY KEY,
  data JSONB,
  layout JSONB
);

INSERT INTO charts (name, data, layout) VALUES
('MedianSalePrice', '{"data": [{"x": [2018, 2019, 2020, 2021, 2022], "y": [480000, 505000, 560000, 680000, 750000], "type": "scatter", "mode": "lines+markers", "name": "Avg. Price", "line": {"color": "#337966"}}]}', '{"title": "Median Sale Price", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 70}, "xaxis": {"title": "Year", "type": "category", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Price ($CAD)", "tickformat": "$,.0f", "gridcolor": "#f0f0f0"}, "hovermode": "x unified", "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('HousingStarts', '{"data": [{"x": ["Jan", "Feb", "Mar", "Apr"], "y": [18000, 19500, 21000, 20500], "type": "bar", "marker": {"color": "#337966"}}]}', '{"title": "Monthly Housing Starts", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 60}, "xaxis": {"title": "Month", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Number of Starts", "gridcolor": "#f0f0f0"}, "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('RentalVacancy', '{"data": [{"y": ["Toronto", "Vancouver", "Montreal", "Calgary"], "x": [1.5, 1.1, 2.8, 3.5], "type": "bar", "orientation": "h", "marker": {"color": "#337966"}}]}', '{"title": "Rental Vacancy Rates (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 100}, "xaxis": {"title": "Vacancy Rate (%)", "range": [0, 5], "gridcolor": "#f0f0f0"}, "yaxis": {"autorange": "reversed", "gridcolor": "#f0f0f0", "showgrid": false}, "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('MortgageRate', '{"data": [{"x": ["Q1 22", "Q2 22", "Q3 22", "Q4 22"], "y": [3.2, 4.0, 4.8, 5.5], "type": "scatter", "mode": "lines+markers", "line": {"color": "#337966"}}]}', '{"title": "5-Year Fixed Mortgage Rate (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 70, "l": 50}, "xaxis": {"title": "Quarter", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Interest Rate (%)", "range": [2, 7], "gridcolor": "#f0f0f0"}, "hovermode": "x unified", "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('PresidentialApproval', '{"data": [{"x": ["Jan", "Feb", "Mar", "Apr"], "y": [42, 44, 45, 43], "type": "line", "name": "Approval", "line": {"color": "#337966"}}, {"x": ["Jan", "Feb", "Mar", "Apr"], "y": [51, 49, 48, 50], "type": "line", "name": "Disapproval", "line": {"color": "#760F17"}}]}', '{"title": "Presidential Approval Rating (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 50}, "xaxis": {"gridcolor": "#f0f0f0"}, "yaxis": {"gridcolor": "#f0f0f0", "range": [0, 100], "title": {"text": "% Rating", "standoff": 10}}, "legend": {"orientation": "h", "yanchor": "bottom", "y": 1.02, "xanchor": "center", "x": 0.5}, "hovermode": "x unified", "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('PartySupport', '{"data": [{"values": [32, 34, 18, 8, 5], "labels": ["Liberal", "Conservative", "NDP", "Bloc", "Green"], "type": "pie", "hole": 0.4, "marker": {"colors": ["#D32F2F", "#1976D2", "#FF9800", "#4CAF50", "#8BC34A"]}}]}', '{"title": "National Party Support (%)", "autosize": true, "margin": {"t": 30, "r": 10, "b": 50, "l": 10}, "legend": {"orientation": "h", "yanchor": "bottom", "y": -0.1, "xanchor": "center", "x": 0.5}, "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('KeyIssues', '{"data": [{"y": ["Housing", "Healthcare", "Economy", "Climate"], "x": [78, 72, 68, 58], "type": "bar", "orientation": "h", "marker": {"color": "#337966"}}]}', '{"title": "Key Voter Issues (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 100}, "xaxis": {"range": [0, 100], "gridcolor": "#f0f0f0", "title": {"text": "% Importance"}}, "yaxis": {"autorange": "reversed", "showgrid": false}, "bargap": 0.2, "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('UnemploymentRate', '{"data": [{"x": ["Jan", "Apr", "Jul", "Oct"], "y": [5.0, 5.1, 5.2, 5.4], "type": "scatter", "mode": "lines+markers", "line": {"color": "#337966"}}]}', '{"title": "Unemployment Rate (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 70, "l": 50}, "xaxis": {"title": "Period", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Rate (%)", "range": [4, 7], "gridcolor": "#f0f0f0"}, "hovermode": "x unified", "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('SectorJobChange', '{"data": [{"x": ["Tech", "Healthcare", "Construction", "Retail"], "y": [15000, 12000, 8000, -5000], "type": "bar", "marker": {"color": ["#337966", "#337966", "#337966", "#760F17"]}}]}', '{"title": "Job Change by Sector", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 60}, "xaxis": {"title": "Sector", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Net Job Change", "gridcolor": "#f0f0f0"}, "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('ProvincialEmployment', '{"data": [{"x": ["ON", "QC", "BC", "AB"], "y": [60.5, 61.2, 59.8, 62.1], "type": "bar", "marker": {"color": "#337966"}}]}', '{"title": "Provincial Employment Rate (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 50}, "xaxis": {"title": "Province", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Employment Rate (%)", "range": [55, 65], "gridcolor": "#f0f0f0"}, "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}'),
('WageGrowth', '{"data": [{"x": [2020, 2021, 2022, 2023], "y": [2.1, 2.5, 3.1, 4.5], "type": "scatter", "mode": "lines+markers", "line": {"color": "#337966"}}]}', '{"title": "Avg. Hourly Wage Growth (%)", "autosize": true, "margin": {"t": 30, "r": 30, "b": 50, "l": 50}, "xaxis": {"title": "Year", "type": "category", "gridcolor": "#f0f0f0"}, "yaxis": {"title": "Growth (%)", "range": [0, 6], "gridcolor": "#f0f0f0"}, "hovermode": "x unified", "paper_bgcolor": "rgba(0,0,0,0)", "plot_bgcolor": "rgba(0,0,0,0)"}');
